directories:
  output: dist
  buildResources: build
appId: com.electron-app2.id
productName: electron-app2
publish:
  - provider: generic
    url: http://127.0.0.1:8080/
win:
  target: nsis
files: []
electronVersion: 30.0.9
